//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document()
        {
            this.DocumentApprovals = new HashSet<DocumentApproval>();
            this.DocumentChangeLogs = new HashSet<DocumentChangeLog>();
            this.DocumentDepartments = new HashSet<DocumentDepartment>();
            this.FavoriteDocuments = new HashSet<FavoriteDocument>();
        }
    
        public int DocumentId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> DocumentTypeId { get; set; }
        public int UploaderID { get; set; }
        public string FilePath { get; set; }
        public string ApprovalStatus { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public Nullable<long> FileSize { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentApproval> DocumentApprovals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentChangeLog> DocumentChangeLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentDepartment> DocumentDepartments { get; set; }
        public virtual DocumentType DocumentType { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FavoriteDocument> FavoriteDocuments { get; set; }
    }
}
