//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentApproval
    {
        public int ApprovalID { get; set; }
        public int DocumentID { get; set; }
        public int UploaderID { get; set; }
        public Nullable<int> ApproverID { get; set; }
        public string Status { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> DateUploaded { get; set; }
        public Nullable<System.DateTime> DateReviewed { get; set; }
    
        public virtual User User { get; set; }
        public virtual Document Document { get; set; }
        public virtual User User1 { get; set; }
    }
}
