//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentChangeLog
    {
        public int ChangeID { get; set; }
        public int DocumentID { get; set; }
        public int ChangedBy { get; set; }
        public string ChangeType { get; set; }
        public string ChangeDescription { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual User User { get; set; }
    }
}
